/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VilkarRouteImport } from './routes/vilkar'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PersonvernRouteImport } from './routes/personvern'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as MapTestRouteImport } from './routes/map-test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HjelpRouteImport } from './routes/hjelp'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as SharedTripIdRouteImport } from './routes/shared.$tripId'
import { Route as SharedShareTokenRouteImport } from './routes/shared.$shareToken'
import { Route as RestoreTokenRouteImport } from './routes/restore.$token'
import { Route as PartnerRegisterRouteImport } from './routes/partner.register'
import { Route as PartnerDashboardRouteImport } from './routes/partner.dashboard'
import { Route as LiveTokenRouteImport } from './routes/live.$token'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTripsRouteImport } from './routes/admin.trips'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminBenefitsRouteImport } from './routes/admin.benefits'
import { Route as AdminAudienceRouteImport } from './routes/admin.audience'
import { Route as AdminAdvertisersRouteImport } from './routes/admin.advertisers'
import { Route as AppTripsRouteImport } from './routes/_app.trips'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoadbookRouteImport } from './routes/_app.roadbook'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppMapsCheckRouteImport } from './routes/_app.maps-check'
import { Route as AppGarageRouteImport } from './routes/_app.garage'
import { Route as AppFordelerRouteImport } from './routes/_app.fordeler'
import { Route as AppExploreRouteImport } from './routes/_app.explore'
import { Route as PartnerDashboardIndexRouteImport } from './routes/partner.dashboard.index'
import { Route as PartnerDashboardInvoicesRouteImport } from './routes/partner.dashboard.invoices'
import { Route as PartnerDashboardBenefitsRouteImport } from './routes/partner.dashboard.benefits'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicPoiSearchRouteImport } from './routes/api/public.poi-search'
import { Route as ApiPublicMapConfigRouteImport } from './routes/api/public.map-config'
import { Route as ApiPublicGooglePlacesRouteImport } from './routes/api/public/google-places'
import { Route as ApiPublicDirectionsRouteImport } from './routes/api/public/directions'
import { Route as AppTripsNewRouteImport } from './routes/_app.trips.new'
import { Route as AppTripsTripIdRouteImport } from './routes/_app.trips.$tripId'
import { Route as PartnerDashboardCampaignNewRouteImport } from './routes/partner.dashboard.campaign.new'
import { Route as PartnerDashboardCampaignIdRouteImport } from './routes/partner.dashboard.campaign.$id'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksTripRemindersRouteImport } from './routes/api/public/hooks/trip-reminders'
import { Route as ApiPublicHooksPartnersMonthlyResetRouteImport } from './routes/api/public/hooks/partners-monthly-reset'
import { Route as ApiPublicCronGeneratePartnerInvoicesRouteImport } from './routes/api/public/cron/generate-partner-invoices'
import { Route as AppTripsTripIdRoadbookRouteImport } from './routes/_app.trips.$tripId.roadbook'
import { Route as AppTripsTripIdStopsStopIdRouteImport } from './routes/_app.trips.$tripId.stops.$stopId'

const VilkarRoute = VilkarRouteImport.update({
  id: '/vilkar',
  path: '/vilkar',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonvernRoute = PersonvernRouteImport.update({
  id: '/personvern',
  path: '/personvern',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const MapTestRoute = MapTestRouteImport.update({
  id: '/map-test',
  path: '/map-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HjelpRoute = HjelpRouteImport.update({
  id: '/hjelp',
  path: '/hjelp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTripIdRoute = SharedTripIdRouteImport.update({
  id: '/shared/$tripId',
  path: '/shared/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedShareTokenRoute = SharedShareTokenRouteImport.update({
  id: '/shared/$shareToken',
  path: '/shared/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoreTokenRoute = RestoreTokenRouteImport.update({
  id: '/restore/$token',
  path: '/restore/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRegisterRoute = PartnerRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PartnerRoute,
} as any)
const PartnerDashboardRoute = PartnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PartnerRoute,
} as any)
const LiveTokenRoute = LiveTokenRouteImport.update({
  id: '/live/$token',
  path: '/live/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTripsRoute = AdminTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBenefitsRoute = AdminBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAudienceRoute = AdminAudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdvertisersRoute = AdminAdvertisersRouteImport.update({
  id: '/advertisers',
  path: '/advertisers',
  getParentRoute: () => AdminRoute,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadbookRoute = AppRoadbookRouteImport.update({
  id: '/roadbook',
  path: '/roadbook',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMapsCheckRoute = AppMapsCheckRouteImport.update({
  id: '/maps-check',
  path: '/maps-check',
  getParentRoute: () => AppRoute,
} as any)
const AppGarageRoute = AppGarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => AppRoute,
} as any)
const AppFordelerRoute = AppFordelerRouteImport.update({
  id: '/fordeler',
  path: '/fordeler',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const PartnerDashboardIndexRoute = PartnerDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerDashboardRoute,
} as any)
const PartnerDashboardInvoicesRoute =
  PartnerDashboardInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => PartnerDashboardRoute,
  } as any)
const PartnerDashboardBenefitsRoute =
  PartnerDashboardBenefitsRouteImport.update({
    id: '/benefits',
    path: '/benefits',
    getParentRoute: () => PartnerDashboardRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPoiSearchRoute = ApiPublicPoiSearchRouteImport.update({
  id: '/api/public/poi-search',
  path: '/api/public/poi-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMapConfigRoute = ApiPublicMapConfigRouteImport.update({
  id: '/api/public/map-config',
  path: '/api/public/map-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGooglePlacesRoute = ApiPublicGooglePlacesRouteImport.update({
  id: '/api/public/google-places',
  path: '/api/public/google-places',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDirectionsRoute = ApiPublicDirectionsRouteImport.update({
  id: '/api/public/directions',
  path: '/api/public/directions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTripsNewRoute = AppTripsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdRoute = AppTripsTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => AppTripsRoute,
} as any)
const PartnerDashboardCampaignNewRoute =
  PartnerDashboardCampaignNewRouteImport.update({
    id: '/campaign/new',
    path: '/campaign/new',
    getParentRoute: () => PartnerDashboardRoute,
  } as any)
const PartnerDashboardCampaignIdRoute =
  PartnerDashboardCampaignIdRouteImport.update({
    id: '/campaign/$id',
    path: '/campaign/$id',
    getParentRoute: () => PartnerDashboardRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTripRemindersRoute =
  ApiPublicHooksTripRemindersRouteImport.update({
    id: '/api/public/hooks/trip-reminders',
    path: '/api/public/hooks/trip-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPartnersMonthlyResetRoute =
  ApiPublicHooksPartnersMonthlyResetRouteImport.update({
    id: '/api/public/hooks/partners-monthly-reset',
    path: '/api/public/hooks/partners-monthly-reset',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronGeneratePartnerInvoicesRoute =
  ApiPublicCronGeneratePartnerInvoicesRouteImport.update({
    id: '/api/public/cron/generate-partner-invoices',
    path: '/api/public/cron/generate-partner-invoices',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppTripsTripIdRoadbookRoute = AppTripsTripIdRoadbookRouteImport.update({
  id: '/roadbook',
  path: '/roadbook',
  getParentRoute: () => AppTripsTripIdRoute,
} as any)
const AppTripsTripIdStopsStopIdRoute =
  AppTripsTripIdStopsStopIdRouteImport.update({
    id: '/stops/$stopId',
    path: '/stops/$stopId',
    getParentRoute: () => AppTripsTripIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/hjelp': typeof HjelpRoute
  '/login': typeof LoginRoute
  '/map-test': typeof MapTestRoute
  '/partner': typeof PartnerRouteWithChildren
  '/personvern': typeof PersonvernRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vilkar': typeof VilkarRoute
  '/explore': typeof AppExploreRoute
  '/fordeler': typeof AppFordelerRoute
  '/garage': typeof AppGarageRoute
  '/maps-check': typeof AppMapsCheckRoute
  '/onboarding': typeof AppOnboardingRoute
  '/roadbook': typeof AppRoadbookRoute
  '/settings': typeof AppSettingsRoute
  '/trips': typeof AppTripsRouteWithChildren
  '/admin/advertisers': typeof AdminAdvertisersRoute
  '/admin/audience': typeof AdminAudienceRoute
  '/admin/benefits': typeof AdminBenefitsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/live/$token': typeof LiveTokenRoute
  '/partner/dashboard': typeof PartnerDashboardRouteWithChildren
  '/partner/register': typeof PartnerRegisterRoute
  '/restore/$token': typeof RestoreTokenRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/shared/$tripId': typeof SharedTripIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/trips/new': typeof AppTripsNewRoute
  '/api/public/directions': typeof ApiPublicDirectionsRoute
  '/api/public/google-places': typeof ApiPublicGooglePlacesRoute
  '/api/public/map-config': typeof ApiPublicMapConfigRoute
  '/api/public/poi-search': typeof ApiPublicPoiSearchRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/partner/dashboard/benefits': typeof PartnerDashboardBenefitsRoute
  '/partner/dashboard/invoices': typeof PartnerDashboardInvoicesRoute
  '/partner/dashboard/': typeof PartnerDashboardIndexRoute
  '/trips/$tripId/roadbook': typeof AppTripsTripIdRoadbookRoute
  '/api/public/cron/generate-partner-invoices': typeof ApiPublicCronGeneratePartnerInvoicesRoute
  '/api/public/hooks/partners-monthly-reset': typeof ApiPublicHooksPartnersMonthlyResetRoute
  '/api/public/hooks/trip-reminders': typeof ApiPublicHooksTripRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/partner/dashboard/campaign/$id': typeof PartnerDashboardCampaignIdRoute
  '/partner/dashboard/campaign/new': typeof PartnerDashboardCampaignNewRoute
  '/trips/$tripId/stops/$stopId': typeof AppTripsTripIdStopsStopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hjelp': typeof HjelpRoute
  '/login': typeof LoginRoute
  '/map-test': typeof MapTestRoute
  '/personvern': typeof PersonvernRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vilkar': typeof VilkarRoute
  '/explore': typeof AppExploreRoute
  '/fordeler': typeof AppFordelerRoute
  '/garage': typeof AppGarageRoute
  '/maps-check': typeof AppMapsCheckRoute
  '/onboarding': typeof AppOnboardingRoute
  '/roadbook': typeof AppRoadbookRoute
  '/settings': typeof AppSettingsRoute
  '/trips': typeof AppTripsRouteWithChildren
  '/admin/advertisers': typeof AdminAdvertisersRoute
  '/admin/audience': typeof AdminAudienceRoute
  '/admin/benefits': typeof AdminBenefitsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/live/$token': typeof LiveTokenRoute
  '/partner/register': typeof PartnerRegisterRoute
  '/restore/$token': typeof RestoreTokenRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/shared/$tripId': typeof SharedTripIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin': typeof AdminIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/trips/new': typeof AppTripsNewRoute
  '/api/public/directions': typeof ApiPublicDirectionsRoute
  '/api/public/google-places': typeof ApiPublicGooglePlacesRoute
  '/api/public/map-config': typeof ApiPublicMapConfigRoute
  '/api/public/poi-search': typeof ApiPublicPoiSearchRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/partner/dashboard/benefits': typeof PartnerDashboardBenefitsRoute
  '/partner/dashboard/invoices': typeof PartnerDashboardInvoicesRoute
  '/partner/dashboard': typeof PartnerDashboardIndexRoute
  '/trips/$tripId/roadbook': typeof AppTripsTripIdRoadbookRoute
  '/api/public/cron/generate-partner-invoices': typeof ApiPublicCronGeneratePartnerInvoicesRoute
  '/api/public/hooks/partners-monthly-reset': typeof ApiPublicHooksPartnersMonthlyResetRoute
  '/api/public/hooks/trip-reminders': typeof ApiPublicHooksTripRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/partner/dashboard/campaign/$id': typeof PartnerDashboardCampaignIdRoute
  '/partner/dashboard/campaign/new': typeof PartnerDashboardCampaignNewRoute
  '/trips/$tripId/stops/$stopId': typeof AppTripsTripIdStopsStopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/hjelp': typeof HjelpRoute
  '/login': typeof LoginRoute
  '/map-test': typeof MapTestRoute
  '/partner': typeof PartnerRouteWithChildren
  '/personvern': typeof PersonvernRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vilkar': typeof VilkarRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/fordeler': typeof AppFordelerRoute
  '/_app/garage': typeof AppGarageRoute
  '/_app/maps-check': typeof AppMapsCheckRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/roadbook': typeof AppRoadbookRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/trips': typeof AppTripsRouteWithChildren
  '/admin/advertisers': typeof AdminAdvertisersRoute
  '/admin/audience': typeof AdminAudienceRoute
  '/admin/benefits': typeof AdminBenefitsRoute
  '/admin/invoices': typeof AdminInvoicesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/trips': typeof AdminTripsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/live/$token': typeof LiveTokenRoute
  '/partner/dashboard': typeof PartnerDashboardRouteWithChildren
  '/partner/register': typeof PartnerRegisterRoute
  '/restore/$token': typeof RestoreTokenRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/shared/$tripId': typeof SharedTripIdRoute
  '/u/$username': typeof UUsernameRoute
  '/admin/': typeof AdminIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/_app/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/_app/trips/new': typeof AppTripsNewRoute
  '/api/public/directions': typeof ApiPublicDirectionsRoute
  '/api/public/google-places': typeof ApiPublicGooglePlacesRoute
  '/api/public/map-config': typeof ApiPublicMapConfigRoute
  '/api/public/poi-search': typeof ApiPublicPoiSearchRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/partner/dashboard/benefits': typeof PartnerDashboardBenefitsRoute
  '/partner/dashboard/invoices': typeof PartnerDashboardInvoicesRoute
  '/partner/dashboard/': typeof PartnerDashboardIndexRoute
  '/_app/trips/$tripId/roadbook': typeof AppTripsTripIdRoadbookRoute
  '/api/public/cron/generate-partner-invoices': typeof ApiPublicCronGeneratePartnerInvoicesRoute
  '/api/public/hooks/partners-monthly-reset': typeof ApiPublicHooksPartnersMonthlyResetRoute
  '/api/public/hooks/trip-reminders': typeof ApiPublicHooksTripRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/partner/dashboard/campaign/$id': typeof PartnerDashboardCampaignIdRoute
  '/partner/dashboard/campaign/new': typeof PartnerDashboardCampaignNewRoute
  '/_app/trips/$tripId/stops/$stopId': typeof AppTripsTripIdStopsStopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/hjelp'
    | '/login'
    | '/map-test'
    | '/partner'
    | '/personvern'
    | '/pricing'
    | '/signup'
    | '/unsubscribe'
    | '/vilkar'
    | '/explore'
    | '/fordeler'
    | '/garage'
    | '/maps-check'
    | '/onboarding'
    | '/roadbook'
    | '/settings'
    | '/trips'
    | '/admin/advertisers'
    | '/admin/audience'
    | '/admin/benefits'
    | '/admin/invoices'
    | '/admin/partners'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/trips'
    | '/admin/users'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/join/$token'
    | '/live/$token'
    | '/partner/dashboard'
    | '/partner/register'
    | '/restore/$token'
    | '/shared/$shareToken'
    | '/shared/$tripId'
    | '/u/$username'
    | '/admin/'
    | '/partner/'
    | '/trips/$tripId'
    | '/trips/new'
    | '/api/public/directions'
    | '/api/public/google-places'
    | '/api/public/map-config'
    | '/api/public/poi-search'
    | '/lovable/email/suppression'
    | '/partner/dashboard/benefits'
    | '/partner/dashboard/invoices'
    | '/partner/dashboard/'
    | '/trips/$tripId/roadbook'
    | '/api/public/cron/generate-partner-invoices'
    | '/api/public/hooks/partners-monthly-reset'
    | '/api/public/hooks/trip-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/partner/dashboard/campaign/$id'
    | '/partner/dashboard/campaign/new'
    | '/trips/$tripId/stops/$stopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hjelp'
    | '/login'
    | '/map-test'
    | '/personvern'
    | '/pricing'
    | '/signup'
    | '/unsubscribe'
    | '/vilkar'
    | '/explore'
    | '/fordeler'
    | '/garage'
    | '/maps-check'
    | '/onboarding'
    | '/roadbook'
    | '/settings'
    | '/trips'
    | '/admin/advertisers'
    | '/admin/audience'
    | '/admin/benefits'
    | '/admin/invoices'
    | '/admin/partners'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/trips'
    | '/admin/users'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/join/$token'
    | '/live/$token'
    | '/partner/register'
    | '/restore/$token'
    | '/shared/$shareToken'
    | '/shared/$tripId'
    | '/u/$username'
    | '/admin'
    | '/partner'
    | '/trips/$tripId'
    | '/trips/new'
    | '/api/public/directions'
    | '/api/public/google-places'
    | '/api/public/map-config'
    | '/api/public/poi-search'
    | '/lovable/email/suppression'
    | '/partner/dashboard/benefits'
    | '/partner/dashboard/invoices'
    | '/partner/dashboard'
    | '/trips/$tripId/roadbook'
    | '/api/public/cron/generate-partner-invoices'
    | '/api/public/hooks/partners-monthly-reset'
    | '/api/public/hooks/trip-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/partner/dashboard/campaign/$id'
    | '/partner/dashboard/campaign/new'
    | '/trips/$tripId/stops/$stopId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/hjelp'
    | '/login'
    | '/map-test'
    | '/partner'
    | '/personvern'
    | '/pricing'
    | '/signup'
    | '/unsubscribe'
    | '/vilkar'
    | '/_app/explore'
    | '/_app/fordeler'
    | '/_app/garage'
    | '/_app/maps-check'
    | '/_app/onboarding'
    | '/_app/roadbook'
    | '/_app/settings'
    | '/_app/trips'
    | '/admin/advertisers'
    | '/admin/audience'
    | '/admin/benefits'
    | '/admin/invoices'
    | '/admin/partners'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/trips'
    | '/admin/users'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/join/$token'
    | '/live/$token'
    | '/partner/dashboard'
    | '/partner/register'
    | '/restore/$token'
    | '/shared/$shareToken'
    | '/shared/$tripId'
    | '/u/$username'
    | '/admin/'
    | '/partner/'
    | '/_app/trips/$tripId'
    | '/_app/trips/new'
    | '/api/public/directions'
    | '/api/public/google-places'
    | '/api/public/map-config'
    | '/api/public/poi-search'
    | '/lovable/email/suppression'
    | '/partner/dashboard/benefits'
    | '/partner/dashboard/invoices'
    | '/partner/dashboard/'
    | '/_app/trips/$tripId/roadbook'
    | '/api/public/cron/generate-partner-invoices'
    | '/api/public/hooks/partners-monthly-reset'
    | '/api/public/hooks/trip-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/partner/dashboard/campaign/$id'
    | '/partner/dashboard/campaign/new'
    | '/_app/trips/$tripId/stops/$stopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  HjelpRoute: typeof HjelpRoute
  LoginRoute: typeof LoginRoute
  MapTestRoute: typeof MapTestRoute
  PartnerRoute: typeof PartnerRouteWithChildren
  PersonvernRoute: typeof PersonvernRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VilkarRoute: typeof VilkarRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  InviteTokenRoute: typeof InviteTokenRoute
  JoinTokenRoute: typeof JoinTokenRoute
  LiveTokenRoute: typeof LiveTokenRoute
  RestoreTokenRoute: typeof RestoreTokenRoute
  SharedShareTokenRoute: typeof SharedShareTokenRoute
  SharedTripIdRoute: typeof SharedTripIdRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicDirectionsRoute: typeof ApiPublicDirectionsRoute
  ApiPublicGooglePlacesRoute: typeof ApiPublicGooglePlacesRoute
  ApiPublicMapConfigRoute: typeof ApiPublicMapConfigRoute
  ApiPublicPoiSearchRoute: typeof ApiPublicPoiSearchRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicCronGeneratePartnerInvoicesRoute: typeof ApiPublicCronGeneratePartnerInvoicesRoute
  ApiPublicHooksPartnersMonthlyResetRoute: typeof ApiPublicHooksPartnersMonthlyResetRoute
  ApiPublicHooksTripRemindersRoute: typeof ApiPublicHooksTripRemindersRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vilkar': {
      id: '/vilkar'
      path: '/vilkar'
      fullPath: '/vilkar'
      preLoaderRoute: typeof VilkarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personvern': {
      id: '/personvern'
      path: '/personvern'
      fullPath: '/personvern'
      preLoaderRoute: typeof PersonvernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-test': {
      id: '/map-test'
      path: '/map-test'
      fullPath: '/map-test'
      preLoaderRoute: typeof MapTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hjelp': {
      id: '/hjelp'
      path: '/hjelp'
      fullPath: '/hjelp'
      preLoaderRoute: typeof HjelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$tripId': {
      id: '/shared/$tripId'
      path: '/shared/$tripId'
      fullPath: '/shared/$tripId'
      preLoaderRoute: typeof SharedTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$shareToken': {
      id: '/shared/$shareToken'
      path: '/shared/$shareToken'
      fullPath: '/shared/$shareToken'
      preLoaderRoute: typeof SharedShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restore/$token': {
      id: '/restore/$token'
      path: '/restore/$token'
      fullPath: '/restore/$token'
      preLoaderRoute: typeof RestoreTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/register': {
      id: '/partner/register'
      path: '/register'
      fullPath: '/partner/register'
      preLoaderRoute: typeof PartnerRegisterRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/partner/dashboard': {
      id: '/partner/dashboard'
      path: '/dashboard'
      fullPath: '/partner/dashboard'
      preLoaderRoute: typeof PartnerDashboardRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/live/$token': {
      id: '/live/$token'
      path: '/live/$token'
      fullPath: '/live/$token'
      preLoaderRoute: typeof LiveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trips': {
      id: '/admin/trips'
      path: '/trips'
      fullPath: '/admin/trips'
      preLoaderRoute: typeof AdminTripsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/benefits': {
      id: '/admin/benefits'
      path: '/benefits'
      fullPath: '/admin/benefits'
      preLoaderRoute: typeof AdminBenefitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audience': {
      id: '/admin/audience'
      path: '/audience'
      fullPath: '/admin/audience'
      preLoaderRoute: typeof AdminAudienceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/advertisers': {
      id: '/admin/advertisers'
      path: '/advertisers'
      fullPath: '/admin/advertisers'
      preLoaderRoute: typeof AdminAdvertisersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/trips': {
      id: '/_app/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadbook': {
      id: '/_app/roadbook'
      path: '/roadbook'
      fullPath: '/roadbook'
      preLoaderRoute: typeof AppRoadbookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maps-check': {
      id: '/_app/maps-check'
      path: '/maps-check'
      fullPath: '/maps-check'
      preLoaderRoute: typeof AppMapsCheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/garage': {
      id: '/_app/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof AppGarageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fordeler': {
      id: '/_app/fordeler'
      path: '/fordeler'
      fullPath: '/fordeler'
      preLoaderRoute: typeof AppFordelerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/partner/dashboard/': {
      id: '/partner/dashboard/'
      path: '/'
      fullPath: '/partner/dashboard/'
      preLoaderRoute: typeof PartnerDashboardIndexRouteImport
      parentRoute: typeof PartnerDashboardRoute
    }
    '/partner/dashboard/invoices': {
      id: '/partner/dashboard/invoices'
      path: '/invoices'
      fullPath: '/partner/dashboard/invoices'
      preLoaderRoute: typeof PartnerDashboardInvoicesRouteImport
      parentRoute: typeof PartnerDashboardRoute
    }
    '/partner/dashboard/benefits': {
      id: '/partner/dashboard/benefits'
      path: '/benefits'
      fullPath: '/partner/dashboard/benefits'
      preLoaderRoute: typeof PartnerDashboardBenefitsRouteImport
      parentRoute: typeof PartnerDashboardRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/poi-search': {
      id: '/api/public/poi-search'
      path: '/api/public/poi-search'
      fullPath: '/api/public/poi-search'
      preLoaderRoute: typeof ApiPublicPoiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/map-config': {
      id: '/api/public/map-config'
      path: '/api/public/map-config'
      fullPath: '/api/public/map-config'
      preLoaderRoute: typeof ApiPublicMapConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-places': {
      id: '/api/public/google-places'
      path: '/api/public/google-places'
      fullPath: '/api/public/google-places'
      preLoaderRoute: typeof ApiPublicGooglePlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/directions': {
      id: '/api/public/directions'
      path: '/api/public/directions'
      fullPath: '/api/public/directions'
      preLoaderRoute: typeof ApiPublicDirectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trips/new': {
      id: '/_app/trips/new'
      path: '/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AppTripsNewRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId': {
      id: '/_app/trips/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AppTripsTripIdRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/partner/dashboard/campaign/new': {
      id: '/partner/dashboard/campaign/new'
      path: '/campaign/new'
      fullPath: '/partner/dashboard/campaign/new'
      preLoaderRoute: typeof PartnerDashboardCampaignNewRouteImport
      parentRoute: typeof PartnerDashboardRoute
    }
    '/partner/dashboard/campaign/$id': {
      id: '/partner/dashboard/campaign/$id'
      path: '/campaign/$id'
      fullPath: '/partner/dashboard/campaign/$id'
      preLoaderRoute: typeof PartnerDashboardCampaignIdRouteImport
      parentRoute: typeof PartnerDashboardRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trip-reminders': {
      id: '/api/public/hooks/trip-reminders'
      path: '/api/public/hooks/trip-reminders'
      fullPath: '/api/public/hooks/trip-reminders'
      preLoaderRoute: typeof ApiPublicHooksTripRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/partners-monthly-reset': {
      id: '/api/public/hooks/partners-monthly-reset'
      path: '/api/public/hooks/partners-monthly-reset'
      fullPath: '/api/public/hooks/partners-monthly-reset'
      preLoaderRoute: typeof ApiPublicHooksPartnersMonthlyResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/generate-partner-invoices': {
      id: '/api/public/cron/generate-partner-invoices'
      path: '/api/public/cron/generate-partner-invoices'
      fullPath: '/api/public/cron/generate-partner-invoices'
      preLoaderRoute: typeof ApiPublicCronGeneratePartnerInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trips/$tripId/roadbook': {
      id: '/_app/trips/$tripId/roadbook'
      path: '/roadbook'
      fullPath: '/trips/$tripId/roadbook'
      preLoaderRoute: typeof AppTripsTripIdRoadbookRouteImport
      parentRoute: typeof AppTripsTripIdRoute
    }
    '/_app/trips/$tripId/stops/$stopId': {
      id: '/_app/trips/$tripId/stops/$stopId'
      path: '/stops/$stopId'
      fullPath: '/trips/$tripId/stops/$stopId'
      preLoaderRoute: typeof AppTripsTripIdStopsStopIdRouteImport
      parentRoute: typeof AppTripsTripIdRoute
    }
  }
}

interface AppTripsTripIdRouteChildren {
  AppTripsTripIdRoadbookRoute: typeof AppTripsTripIdRoadbookRoute
  AppTripsTripIdStopsStopIdRoute: typeof AppTripsTripIdStopsStopIdRoute
}

const AppTripsTripIdRouteChildren: AppTripsTripIdRouteChildren = {
  AppTripsTripIdRoadbookRoute: AppTripsTripIdRoadbookRoute,
  AppTripsTripIdStopsStopIdRoute: AppTripsTripIdStopsStopIdRoute,
}

const AppTripsTripIdRouteWithChildren = AppTripsTripIdRoute._addFileChildren(
  AppTripsTripIdRouteChildren,
)

interface AppTripsRouteChildren {
  AppTripsTripIdRoute: typeof AppTripsTripIdRouteWithChildren
  AppTripsNewRoute: typeof AppTripsNewRoute
}

const AppTripsRouteChildren: AppTripsRouteChildren = {
  AppTripsTripIdRoute: AppTripsTripIdRouteWithChildren,
  AppTripsNewRoute: AppTripsNewRoute,
}

const AppTripsRouteWithChildren = AppTripsRoute._addFileChildren(
  AppTripsRouteChildren,
)

interface AppRouteChildren {
  AppExploreRoute: typeof AppExploreRoute
  AppFordelerRoute: typeof AppFordelerRoute
  AppGarageRoute: typeof AppGarageRoute
  AppMapsCheckRoute: typeof AppMapsCheckRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppRoadbookRoute: typeof AppRoadbookRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTripsRoute: typeof AppTripsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppExploreRoute: AppExploreRoute,
  AppFordelerRoute: AppFordelerRoute,
  AppGarageRoute: AppGarageRoute,
  AppMapsCheckRoute: AppMapsCheckRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppRoadbookRoute: AppRoadbookRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTripsRoute: AppTripsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAdvertisersRoute: typeof AdminAdvertisersRoute
  AdminAudienceRoute: typeof AdminAudienceRoute
  AdminBenefitsRoute: typeof AdminBenefitsRoute
  AdminInvoicesRoute: typeof AdminInvoicesRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTripsRoute: typeof AdminTripsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdvertisersRoute: AdminAdvertisersRoute,
  AdminAudienceRoute: AdminAudienceRoute,
  AdminBenefitsRoute: AdminBenefitsRoute,
  AdminInvoicesRoute: AdminInvoicesRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTripsRoute: AdminTripsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PartnerDashboardRouteChildren {
  PartnerDashboardBenefitsRoute: typeof PartnerDashboardBenefitsRoute
  PartnerDashboardInvoicesRoute: typeof PartnerDashboardInvoicesRoute
  PartnerDashboardIndexRoute: typeof PartnerDashboardIndexRoute
  PartnerDashboardCampaignIdRoute: typeof PartnerDashboardCampaignIdRoute
  PartnerDashboardCampaignNewRoute: typeof PartnerDashboardCampaignNewRoute
}

const PartnerDashboardRouteChildren: PartnerDashboardRouteChildren = {
  PartnerDashboardBenefitsRoute: PartnerDashboardBenefitsRoute,
  PartnerDashboardInvoicesRoute: PartnerDashboardInvoicesRoute,
  PartnerDashboardIndexRoute: PartnerDashboardIndexRoute,
  PartnerDashboardCampaignIdRoute: PartnerDashboardCampaignIdRoute,
  PartnerDashboardCampaignNewRoute: PartnerDashboardCampaignNewRoute,
}

const PartnerDashboardRouteWithChildren =
  PartnerDashboardRoute._addFileChildren(PartnerDashboardRouteChildren)

interface PartnerRouteChildren {
  PartnerDashboardRoute: typeof PartnerDashboardRouteWithChildren
  PartnerRegisterRoute: typeof PartnerRegisterRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerDashboardRoute: PartnerDashboardRouteWithChildren,
  PartnerRegisterRoute: PartnerRegisterRoute,
  PartnerIndexRoute: PartnerIndexRoute,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  HjelpRoute: HjelpRoute,
  LoginRoute: LoginRoute,
  MapTestRoute: MapTestRoute,
  PartnerRoute: PartnerRouteWithChildren,
  PersonvernRoute: PersonvernRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VilkarRoute: VilkarRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  InviteTokenRoute: InviteTokenRoute,
  JoinTokenRoute: JoinTokenRoute,
  LiveTokenRoute: LiveTokenRoute,
  RestoreTokenRoute: RestoreTokenRoute,
  SharedShareTokenRoute: SharedShareTokenRoute,
  SharedTripIdRoute: SharedTripIdRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicDirectionsRoute: ApiPublicDirectionsRoute,
  ApiPublicGooglePlacesRoute: ApiPublicGooglePlacesRoute,
  ApiPublicMapConfigRoute: ApiPublicMapConfigRoute,
  ApiPublicPoiSearchRoute: ApiPublicPoiSearchRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicCronGeneratePartnerInvoicesRoute:
    ApiPublicCronGeneratePartnerInvoicesRoute,
  ApiPublicHooksPartnersMonthlyResetRoute:
    ApiPublicHooksPartnersMonthlyResetRoute,
  ApiPublicHooksTripRemindersRoute: ApiPublicHooksTripRemindersRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
