/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MapTestRouteImport } from './routes/map-test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedTripIdRouteImport } from './routes/shared.$tripId'
import { Route as SharedShareTokenRouteImport } from './routes/shared.$shareToken'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppTripsRouteImport } from './routes/_app.trips'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoadbookRouteImport } from './routes/_app.roadbook'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppMapsCheckRouteImport } from './routes/_app.maps-check'
import { Route as ApiPublicPoiSearchRouteImport } from './routes/api/public.poi-search'
import { Route as ApiPublicMapConfigRouteImport } from './routes/api/public.map-config'
import { Route as ApiPublicGooglePlacesRouteImport } from './routes/api/public/google-places'
import { Route as ApiPublicDirectionsRouteImport } from './routes/api/public/directions'
import { Route as AppTripsNewRouteImport } from './routes/_app.trips.new'
import { Route as AppTripsTripIdRouteImport } from './routes/_app.trips.$tripId'
import { Route as AppTripsTripIdRoadbookRouteImport } from './routes/_app.trips.$tripId.roadbook'
import { Route as AppTripsTripIdStopsStopIdRouteImport } from './routes/_app.trips.$tripId.stops.$stopId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MapTestRoute = MapTestRouteImport.update({
  id: '/map-test',
  path: '/map-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTripIdRoute = SharedTripIdRouteImport.update({
  id: '/shared/$tripId',
  path: '/shared/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedShareTokenRoute = SharedShareTokenRouteImport.update({
  id: '/shared/$shareToken',
  path: '/shared/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadbookRoute = AppRoadbookRouteImport.update({
  id: '/roadbook',
  path: '/roadbook',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMapsCheckRoute = AppMapsCheckRouteImport.update({
  id: '/maps-check',
  path: '/maps-check',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicPoiSearchRoute = ApiPublicPoiSearchRouteImport.update({
  id: '/api/public/poi-search',
  path: '/api/public/poi-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMapConfigRoute = ApiPublicMapConfigRouteImport.update({
  id: '/api/public/map-config',
  path: '/api/public/map-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGooglePlacesRoute = ApiPublicGooglePlacesRouteImport.update({
  id: '/api/public/google-places',
  path: '/api/public/google-places',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDirectionsRoute = ApiPublicDirectionsRouteImport.update({
  id: '/api/public/directions',
  path: '/api/public/directions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTripsNewRoute = AppTripsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdRoute = AppTripsTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdRoadbookRoute = AppTripsTripIdRoadbookRouteImport.update({
  id: '/roadbook',
  path: '/roadbook',
  getParentRoute: () => AppTripsTripIdRoute,
} as any)
const AppTripsTripIdStopsStopIdRoute =
  AppTripsTripIdStopsStopIdRouteImport.update({
    id: '/stops/$stopId',
    path: '/stops/$stopId',
    getParentRoute: () => AppTripsTripIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map-test': typeof MapTestRoute
  '/signup': typeof SignupRoute
  '/maps-check': typeof AppMapsCheckRoute
  '/onboarding': typeof AppOnboardingRoute
  '/roadbook': typeof AppRoadbookRoute
  '/settings': typeof AppSettingsRoute
  '/trips': typeof AppTripsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/shared/$tripId': typeof SharedTripIdRoute
  '/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/trips/new': typeof AppTripsNewRoute
  '/api/public/directions': typeof ApiPublicDirectionsRoute
  '/api/public/google-places': typeof ApiPublicGooglePlacesRoute
  '/api/public/map-config': typeof ApiPublicMapConfigRoute
  '/api/public/poi-search': typeof ApiPublicPoiSearchRoute
  '/trips/$tripId/roadbook': typeof AppTripsTripIdRoadbookRoute
  '/trips/$tripId/stops/$stopId': typeof AppTripsTripIdStopsStopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map-test': typeof MapTestRoute
  '/signup': typeof SignupRoute
  '/maps-check': typeof AppMapsCheckRoute
  '/onboarding': typeof AppOnboardingRoute
  '/roadbook': typeof AppRoadbookRoute
  '/settings': typeof AppSettingsRoute
  '/trips': typeof AppTripsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/shared/$tripId': typeof SharedTripIdRoute
  '/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/trips/new': typeof AppTripsNewRoute
  '/api/public/directions': typeof ApiPublicDirectionsRoute
  '/api/public/google-places': typeof ApiPublicGooglePlacesRoute
  '/api/public/map-config': typeof ApiPublicMapConfigRoute
  '/api/public/poi-search': typeof ApiPublicPoiSearchRoute
  '/trips/$tripId/roadbook': typeof AppTripsTripIdRoadbookRoute
  '/trips/$tripId/stops/$stopId': typeof AppTripsTripIdStopsStopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/map-test': typeof MapTestRoute
  '/signup': typeof SignupRoute
  '/_app/maps-check': typeof AppMapsCheckRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/roadbook': typeof AppRoadbookRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/trips': typeof AppTripsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/invite/$token': typeof InviteTokenRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/shared/$tripId': typeof SharedTripIdRoute
  '/_app/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/_app/trips/new': typeof AppTripsNewRoute
  '/api/public/directions': typeof ApiPublicDirectionsRoute
  '/api/public/google-places': typeof ApiPublicGooglePlacesRoute
  '/api/public/map-config': typeof ApiPublicMapConfigRoute
  '/api/public/poi-search': typeof ApiPublicPoiSearchRoute
  '/_app/trips/$tripId/roadbook': typeof AppTripsTripIdRoadbookRoute
  '/_app/trips/$tripId/stops/$stopId': typeof AppTripsTripIdStopsStopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/map-test'
    | '/signup'
    | '/maps-check'
    | '/onboarding'
    | '/roadbook'
    | '/settings'
    | '/trips'
    | '/auth/callback'
    | '/invite/$token'
    | '/shared/$shareToken'
    | '/shared/$tripId'
    | '/trips/$tripId'
    | '/trips/new'
    | '/api/public/directions'
    | '/api/public/google-places'
    | '/api/public/map-config'
    | '/api/public/poi-search'
    | '/trips/$tripId/roadbook'
    | '/trips/$tripId/stops/$stopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/map-test'
    | '/signup'
    | '/maps-check'
    | '/onboarding'
    | '/roadbook'
    | '/settings'
    | '/trips'
    | '/auth/callback'
    | '/invite/$token'
    | '/shared/$shareToken'
    | '/shared/$tripId'
    | '/trips/$tripId'
    | '/trips/new'
    | '/api/public/directions'
    | '/api/public/google-places'
    | '/api/public/map-config'
    | '/api/public/poi-search'
    | '/trips/$tripId/roadbook'
    | '/trips/$tripId/stops/$stopId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/map-test'
    | '/signup'
    | '/_app/maps-check'
    | '/_app/onboarding'
    | '/_app/roadbook'
    | '/_app/settings'
    | '/_app/trips'
    | '/auth/callback'
    | '/invite/$token'
    | '/shared/$shareToken'
    | '/shared/$tripId'
    | '/_app/trips/$tripId'
    | '/_app/trips/new'
    | '/api/public/directions'
    | '/api/public/google-places'
    | '/api/public/map-config'
    | '/api/public/poi-search'
    | '/_app/trips/$tripId/roadbook'
    | '/_app/trips/$tripId/stops/$stopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapTestRoute: typeof MapTestRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  InviteTokenRoute: typeof InviteTokenRoute
  SharedShareTokenRoute: typeof SharedShareTokenRoute
  SharedTripIdRoute: typeof SharedTripIdRoute
  ApiPublicDirectionsRoute: typeof ApiPublicDirectionsRoute
  ApiPublicGooglePlacesRoute: typeof ApiPublicGooglePlacesRoute
  ApiPublicMapConfigRoute: typeof ApiPublicMapConfigRoute
  ApiPublicPoiSearchRoute: typeof ApiPublicPoiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-test': {
      id: '/map-test'
      path: '/map-test'
      fullPath: '/map-test'
      preLoaderRoute: typeof MapTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$tripId': {
      id: '/shared/$tripId'
      path: '/shared/$tripId'
      fullPath: '/shared/$tripId'
      preLoaderRoute: typeof SharedTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$shareToken': {
      id: '/shared/$shareToken'
      path: '/shared/$shareToken'
      fullPath: '/shared/$shareToken'
      preLoaderRoute: typeof SharedShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trips': {
      id: '/_app/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadbook': {
      id: '/_app/roadbook'
      path: '/roadbook'
      fullPath: '/roadbook'
      preLoaderRoute: typeof AppRoadbookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maps-check': {
      id: '/_app/maps-check'
      path: '/maps-check'
      fullPath: '/maps-check'
      preLoaderRoute: typeof AppMapsCheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/poi-search': {
      id: '/api/public/poi-search'
      path: '/api/public/poi-search'
      fullPath: '/api/public/poi-search'
      preLoaderRoute: typeof ApiPublicPoiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/map-config': {
      id: '/api/public/map-config'
      path: '/api/public/map-config'
      fullPath: '/api/public/map-config'
      preLoaderRoute: typeof ApiPublicMapConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-places': {
      id: '/api/public/google-places'
      path: '/api/public/google-places'
      fullPath: '/api/public/google-places'
      preLoaderRoute: typeof ApiPublicGooglePlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/directions': {
      id: '/api/public/directions'
      path: '/api/public/directions'
      fullPath: '/api/public/directions'
      preLoaderRoute: typeof ApiPublicDirectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trips/new': {
      id: '/_app/trips/new'
      path: '/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AppTripsNewRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId': {
      id: '/_app/trips/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AppTripsTripIdRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId/roadbook': {
      id: '/_app/trips/$tripId/roadbook'
      path: '/roadbook'
      fullPath: '/trips/$tripId/roadbook'
      preLoaderRoute: typeof AppTripsTripIdRoadbookRouteImport
      parentRoute: typeof AppTripsTripIdRoute
    }
    '/_app/trips/$tripId/stops/$stopId': {
      id: '/_app/trips/$tripId/stops/$stopId'
      path: '/stops/$stopId'
      fullPath: '/trips/$tripId/stops/$stopId'
      preLoaderRoute: typeof AppTripsTripIdStopsStopIdRouteImport
      parentRoute: typeof AppTripsTripIdRoute
    }
  }
}

interface AppTripsTripIdRouteChildren {
  AppTripsTripIdRoadbookRoute: typeof AppTripsTripIdRoadbookRoute
  AppTripsTripIdStopsStopIdRoute: typeof AppTripsTripIdStopsStopIdRoute
}

const AppTripsTripIdRouteChildren: AppTripsTripIdRouteChildren = {
  AppTripsTripIdRoadbookRoute: AppTripsTripIdRoadbookRoute,
  AppTripsTripIdStopsStopIdRoute: AppTripsTripIdStopsStopIdRoute,
}

const AppTripsTripIdRouteWithChildren = AppTripsTripIdRoute._addFileChildren(
  AppTripsTripIdRouteChildren,
)

interface AppTripsRouteChildren {
  AppTripsTripIdRoute: typeof AppTripsTripIdRouteWithChildren
  AppTripsNewRoute: typeof AppTripsNewRoute
}

const AppTripsRouteChildren: AppTripsRouteChildren = {
  AppTripsTripIdRoute: AppTripsTripIdRouteWithChildren,
  AppTripsNewRoute: AppTripsNewRoute,
}

const AppTripsRouteWithChildren = AppTripsRoute._addFileChildren(
  AppTripsRouteChildren,
)

interface AppRouteChildren {
  AppMapsCheckRoute: typeof AppMapsCheckRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppRoadbookRoute: typeof AppRoadbookRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTripsRoute: typeof AppTripsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppMapsCheckRoute: AppMapsCheckRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppRoadbookRoute: AppRoadbookRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTripsRoute: AppTripsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MapTestRoute: MapTestRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  InviteTokenRoute: InviteTokenRoute,
  SharedShareTokenRoute: SharedShareTokenRoute,
  SharedTripIdRoute: SharedTripIdRoute,
  ApiPublicDirectionsRoute: ApiPublicDirectionsRoute,
  ApiPublicGooglePlacesRoute: ApiPublicGooglePlacesRoute,
  ApiPublicMapConfigRoute: ApiPublicMapConfigRoute,
  ApiPublicPoiSearchRoute: ApiPublicPoiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
