/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MapTestRouteImport } from './routes/map-test'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedTripIdRouteImport } from './routes/shared.$tripId'
import { Route as SharedShareTokenRouteImport } from './routes/shared.$shareToken'
import { Route as RestoreTokenRouteImport } from './routes/restore.$token'
import { Route as LiveTokenRouteImport } from './routes/live.$token'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppTripsRouteImport } from './routes/_app.trips'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRoadbookRouteImport } from './routes/_app.roadbook'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppMapsCheckRouteImport } from './routes/_app.maps-check'
import { Route as AppGarageRouteImport } from './routes/_app.garage'
import { Route as AppExploreRouteImport } from './routes/_app.explore'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicPoiSearchRouteImport } from './routes/api/public.poi-search'
import { Route as ApiPublicMapConfigRouteImport } from './routes/api/public.map-config'
import { Route as ApiPublicGooglePlacesRouteImport } from './routes/api/public/google-places'
import { Route as ApiPublicDirectionsRouteImport } from './routes/api/public/directions'
import { Route as AppTripsNewRouteImport } from './routes/_app.trips.new'
import { Route as AppTripsTripIdRouteImport } from './routes/_app.trips.$tripId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksTripRemindersRouteImport } from './routes/api/public/hooks/trip-reminders'
import { Route as AppTripsTripIdRoadbookRouteImport } from './routes/_app.trips.$tripId.roadbook'
import { Route as AppTripsTripIdStopsStopIdRouteImport } from './routes/_app.trips.$tripId.stops.$stopId'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MapTestRoute = MapTestRouteImport.update({
  id: '/map-test',
  path: '/map-test',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTripIdRoute = SharedTripIdRouteImport.update({
  id: '/shared/$tripId',
  path: '/shared/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedShareTokenRoute = SharedShareTokenRouteImport.update({
  id: '/shared/$shareToken',
  path: '/shared/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoreTokenRoute = RestoreTokenRouteImport.update({
  id: '/restore/$token',
  path: '/restore/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveTokenRoute = LiveTokenRouteImport.update({
  id: '/live/$token',
  path: '/live/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTripsRoute = AppTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadbookRoute = AppRoadbookRouteImport.update({
  id: '/roadbook',
  path: '/roadbook',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMapsCheckRoute = AppMapsCheckRouteImport.update({
  id: '/maps-check',
  path: '/maps-check',
  getParentRoute: () => AppRoute,
} as any)
const AppGarageRoute = AppGarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPoiSearchRoute = ApiPublicPoiSearchRouteImport.update({
  id: '/api/public/poi-search',
  path: '/api/public/poi-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMapConfigRoute = ApiPublicMapConfigRouteImport.update({
  id: '/api/public/map-config',
  path: '/api/public/map-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGooglePlacesRoute = ApiPublicGooglePlacesRouteImport.update({
  id: '/api/public/google-places',
  path: '/api/public/google-places',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDirectionsRoute = ApiPublicDirectionsRouteImport.update({
  id: '/api/public/directions',
  path: '/api/public/directions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTripsNewRoute = AppTripsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppTripsRoute,
} as any)
const AppTripsTripIdRoute = AppTripsTripIdRouteImport.update({
  id: '/$tripId',
  path: '/$tripId',
  getParentRoute: () => AppTripsRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTripRemindersRoute =
  ApiPublicHooksTripRemindersRouteImport.update({
    id: '/api/public/hooks/trip-reminders',
    path: '/api/public/hooks/trip-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppTripsTripIdRoadbookRoute = AppTripsTripIdRoadbookRouteImport.update({
  id: '/roadbook',
  path: '/roadbook',
  getParentRoute: () => AppTripsTripIdRoute,
} as any)
const AppTripsTripIdStopsStopIdRoute =
  AppTripsTripIdStopsStopIdRouteImport.update({
    id: '/stops/$stopId',
    path: '/stops/$stopId',
    getParentRoute: () => AppTripsTripIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map-test': typeof MapTestRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/explore': typeof AppExploreRoute
  '/garage': typeof AppGarageRoute
  '/maps-check': typeof AppMapsCheckRoute
  '/onboarding': typeof AppOnboardingRoute
  '/roadbook': typeof AppRoadbookRoute
  '/settings': typeof AppSettingsRoute
  '/trips': typeof AppTripsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/live/$token': typeof LiveTokenRoute
  '/restore/$token': typeof RestoreTokenRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/shared/$tripId': typeof SharedTripIdRoute
  '/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/trips/new': typeof AppTripsNewRoute
  '/api/public/directions': typeof ApiPublicDirectionsRoute
  '/api/public/google-places': typeof ApiPublicGooglePlacesRoute
  '/api/public/map-config': typeof ApiPublicMapConfigRoute
  '/api/public/poi-search': typeof ApiPublicPoiSearchRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/trips/$tripId/roadbook': typeof AppTripsTripIdRoadbookRoute
  '/api/public/hooks/trip-reminders': typeof ApiPublicHooksTripRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/trips/$tripId/stops/$stopId': typeof AppTripsTripIdStopsStopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/map-test': typeof MapTestRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/explore': typeof AppExploreRoute
  '/garage': typeof AppGarageRoute
  '/maps-check': typeof AppMapsCheckRoute
  '/onboarding': typeof AppOnboardingRoute
  '/roadbook': typeof AppRoadbookRoute
  '/settings': typeof AppSettingsRoute
  '/trips': typeof AppTripsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/live/$token': typeof LiveTokenRoute
  '/restore/$token': typeof RestoreTokenRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/shared/$tripId': typeof SharedTripIdRoute
  '/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/trips/new': typeof AppTripsNewRoute
  '/api/public/directions': typeof ApiPublicDirectionsRoute
  '/api/public/google-places': typeof ApiPublicGooglePlacesRoute
  '/api/public/map-config': typeof ApiPublicMapConfigRoute
  '/api/public/poi-search': typeof ApiPublicPoiSearchRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/trips/$tripId/roadbook': typeof AppTripsTripIdRoadbookRoute
  '/api/public/hooks/trip-reminders': typeof ApiPublicHooksTripRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/trips/$tripId/stops/$stopId': typeof AppTripsTripIdStopsStopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/map-test': typeof MapTestRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/garage': typeof AppGarageRoute
  '/_app/maps-check': typeof AppMapsCheckRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/roadbook': typeof AppRoadbookRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/trips': typeof AppTripsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join/$token': typeof JoinTokenRoute
  '/live/$token': typeof LiveTokenRoute
  '/restore/$token': typeof RestoreTokenRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/shared/$tripId': typeof SharedTripIdRoute
  '/_app/trips/$tripId': typeof AppTripsTripIdRouteWithChildren
  '/_app/trips/new': typeof AppTripsNewRoute
  '/api/public/directions': typeof ApiPublicDirectionsRoute
  '/api/public/google-places': typeof ApiPublicGooglePlacesRoute
  '/api/public/map-config': typeof ApiPublicMapConfigRoute
  '/api/public/poi-search': typeof ApiPublicPoiSearchRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_app/trips/$tripId/roadbook': typeof AppTripsTripIdRoadbookRoute
  '/api/public/hooks/trip-reminders': typeof ApiPublicHooksTripRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_app/trips/$tripId/stops/$stopId': typeof AppTripsTripIdStopsStopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/map-test'
    | '/signup'
    | '/unsubscribe'
    | '/explore'
    | '/garage'
    | '/maps-check'
    | '/onboarding'
    | '/roadbook'
    | '/settings'
    | '/trips'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/join/$token'
    | '/live/$token'
    | '/restore/$token'
    | '/shared/$shareToken'
    | '/shared/$tripId'
    | '/trips/$tripId'
    | '/trips/new'
    | '/api/public/directions'
    | '/api/public/google-places'
    | '/api/public/map-config'
    | '/api/public/poi-search'
    | '/lovable/email/suppression'
    | '/trips/$tripId/roadbook'
    | '/api/public/hooks/trip-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/trips/$tripId/stops/$stopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/map-test'
    | '/signup'
    | '/unsubscribe'
    | '/explore'
    | '/garage'
    | '/maps-check'
    | '/onboarding'
    | '/roadbook'
    | '/settings'
    | '/trips'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/join/$token'
    | '/live/$token'
    | '/restore/$token'
    | '/shared/$shareToken'
    | '/shared/$tripId'
    | '/trips/$tripId'
    | '/trips/new'
    | '/api/public/directions'
    | '/api/public/google-places'
    | '/api/public/map-config'
    | '/api/public/poi-search'
    | '/lovable/email/suppression'
    | '/trips/$tripId/roadbook'
    | '/api/public/hooks/trip-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/trips/$tripId/stops/$stopId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/map-test'
    | '/signup'
    | '/unsubscribe'
    | '/_app/explore'
    | '/_app/garage'
    | '/_app/maps-check'
    | '/_app/onboarding'
    | '/_app/roadbook'
    | '/_app/settings'
    | '/_app/trips'
    | '/auth/callback'
    | '/email/unsubscribe'
    | '/invite/$token'
    | '/join/$token'
    | '/live/$token'
    | '/restore/$token'
    | '/shared/$shareToken'
    | '/shared/$tripId'
    | '/_app/trips/$tripId'
    | '/_app/trips/new'
    | '/api/public/directions'
    | '/api/public/google-places'
    | '/api/public/map-config'
    | '/api/public/poi-search'
    | '/lovable/email/suppression'
    | '/_app/trips/$tripId/roadbook'
    | '/api/public/hooks/trip-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_app/trips/$tripId/stops/$stopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapTestRoute: typeof MapTestRoute
  SignupRoute: typeof SignupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  InviteTokenRoute: typeof InviteTokenRoute
  JoinTokenRoute: typeof JoinTokenRoute
  LiveTokenRoute: typeof LiveTokenRoute
  RestoreTokenRoute: typeof RestoreTokenRoute
  SharedShareTokenRoute: typeof SharedShareTokenRoute
  SharedTripIdRoute: typeof SharedTripIdRoute
  ApiPublicDirectionsRoute: typeof ApiPublicDirectionsRoute
  ApiPublicGooglePlacesRoute: typeof ApiPublicGooglePlacesRoute
  ApiPublicMapConfigRoute: typeof ApiPublicMapConfigRoute
  ApiPublicPoiSearchRoute: typeof ApiPublicPoiSearchRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksTripRemindersRoute: typeof ApiPublicHooksTripRemindersRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-test': {
      id: '/map-test'
      path: '/map-test'
      fullPath: '/map-test'
      preLoaderRoute: typeof MapTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$tripId': {
      id: '/shared/$tripId'
      path: '/shared/$tripId'
      fullPath: '/shared/$tripId'
      preLoaderRoute: typeof SharedTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$shareToken': {
      id: '/shared/$shareToken'
      path: '/shared/$shareToken'
      fullPath: '/shared/$shareToken'
      preLoaderRoute: typeof SharedShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restore/$token': {
      id: '/restore/$token'
      path: '/restore/$token'
      fullPath: '/restore/$token'
      preLoaderRoute: typeof RestoreTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$token': {
      id: '/live/$token'
      path: '/live/$token'
      fullPath: '/live/$token'
      preLoaderRoute: typeof LiveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trips': {
      id: '/_app/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof AppTripsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadbook': {
      id: '/_app/roadbook'
      path: '/roadbook'
      fullPath: '/roadbook'
      preLoaderRoute: typeof AppRoadbookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/maps-check': {
      id: '/_app/maps-check'
      path: '/maps-check'
      fullPath: '/maps-check'
      preLoaderRoute: typeof AppMapsCheckRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/garage': {
      id: '/_app/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof AppGarageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/poi-search': {
      id: '/api/public/poi-search'
      path: '/api/public/poi-search'
      fullPath: '/api/public/poi-search'
      preLoaderRoute: typeof ApiPublicPoiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/map-config': {
      id: '/api/public/map-config'
      path: '/api/public/map-config'
      fullPath: '/api/public/map-config'
      preLoaderRoute: typeof ApiPublicMapConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-places': {
      id: '/api/public/google-places'
      path: '/api/public/google-places'
      fullPath: '/api/public/google-places'
      preLoaderRoute: typeof ApiPublicGooglePlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/directions': {
      id: '/api/public/directions'
      path: '/api/public/directions'
      fullPath: '/api/public/directions'
      preLoaderRoute: typeof ApiPublicDirectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trips/new': {
      id: '/_app/trips/new'
      path: '/new'
      fullPath: '/trips/new'
      preLoaderRoute: typeof AppTripsNewRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/_app/trips/$tripId': {
      id: '/_app/trips/$tripId'
      path: '/$tripId'
      fullPath: '/trips/$tripId'
      preLoaderRoute: typeof AppTripsTripIdRouteImport
      parentRoute: typeof AppTripsRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trip-reminders': {
      id: '/api/public/hooks/trip-reminders'
      path: '/api/public/hooks/trip-reminders'
      fullPath: '/api/public/hooks/trip-reminders'
      preLoaderRoute: typeof ApiPublicHooksTripRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/trips/$tripId/roadbook': {
      id: '/_app/trips/$tripId/roadbook'
      path: '/roadbook'
      fullPath: '/trips/$tripId/roadbook'
      preLoaderRoute: typeof AppTripsTripIdRoadbookRouteImport
      parentRoute: typeof AppTripsTripIdRoute
    }
    '/_app/trips/$tripId/stops/$stopId': {
      id: '/_app/trips/$tripId/stops/$stopId'
      path: '/stops/$stopId'
      fullPath: '/trips/$tripId/stops/$stopId'
      preLoaderRoute: typeof AppTripsTripIdStopsStopIdRouteImport
      parentRoute: typeof AppTripsTripIdRoute
    }
  }
}

interface AppTripsTripIdRouteChildren {
  AppTripsTripIdRoadbookRoute: typeof AppTripsTripIdRoadbookRoute
  AppTripsTripIdStopsStopIdRoute: typeof AppTripsTripIdStopsStopIdRoute
}

const AppTripsTripIdRouteChildren: AppTripsTripIdRouteChildren = {
  AppTripsTripIdRoadbookRoute: AppTripsTripIdRoadbookRoute,
  AppTripsTripIdStopsStopIdRoute: AppTripsTripIdStopsStopIdRoute,
}

const AppTripsTripIdRouteWithChildren = AppTripsTripIdRoute._addFileChildren(
  AppTripsTripIdRouteChildren,
)

interface AppTripsRouteChildren {
  AppTripsTripIdRoute: typeof AppTripsTripIdRouteWithChildren
  AppTripsNewRoute: typeof AppTripsNewRoute
}

const AppTripsRouteChildren: AppTripsRouteChildren = {
  AppTripsTripIdRoute: AppTripsTripIdRouteWithChildren,
  AppTripsNewRoute: AppTripsNewRoute,
}

const AppTripsRouteWithChildren = AppTripsRoute._addFileChildren(
  AppTripsRouteChildren,
)

interface AppRouteChildren {
  AppExploreRoute: typeof AppExploreRoute
  AppGarageRoute: typeof AppGarageRoute
  AppMapsCheckRoute: typeof AppMapsCheckRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppRoadbookRoute: typeof AppRoadbookRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTripsRoute: typeof AppTripsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppExploreRoute: AppExploreRoute,
  AppGarageRoute: AppGarageRoute,
  AppMapsCheckRoute: AppMapsCheckRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppRoadbookRoute: AppRoadbookRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTripsRoute: AppTripsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  MapTestRoute: MapTestRoute,
  SignupRoute: SignupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  InviteTokenRoute: InviteTokenRoute,
  JoinTokenRoute: JoinTokenRoute,
  LiveTokenRoute: LiveTokenRoute,
  RestoreTokenRoute: RestoreTokenRoute,
  SharedShareTokenRoute: SharedShareTokenRoute,
  SharedTripIdRoute: SharedTripIdRoute,
  ApiPublicDirectionsRoute: ApiPublicDirectionsRoute,
  ApiPublicGooglePlacesRoute: ApiPublicGooglePlacesRoute,
  ApiPublicMapConfigRoute: ApiPublicMapConfigRoute,
  ApiPublicPoiSearchRoute: ApiPublicPoiSearchRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksTripRemindersRoute: ApiPublicHooksTripRemindersRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
